name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: 'true'
      - name: dependencies
        run : |
          sudo apt-get update
          sudo apt-get install zenity libsdl2-dev libopencv-dev -qq
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: 'true'
      - name: build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
